name: Deploy to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'
env:
  GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Clean install dependencies
          run: npm install

        - name: Data Script
          env:
            FETCH_SCRIPT: ${{ secrets.FETCH_SCRIPT }}
          run: |
            echo "$FETCH_SCRIPT" > ./src/data/fetch_data.sh
            chmod +x ./src/data/fetch_data.sh
            ./src/data/fetch_data.sh

        - name: Build
          run: npm run build

        - name: Files stats /dist
          run: |
            echo "Total file count in /dist:"
            find ./dist -type f | wc -l
            echo "Total size of files in /dist:"
            du -sh ./dist
            echo "Individual file sizes in /dist:"
            find ./dist -type f -exec du -h {} +
            
        - name: Purge
          if: false
          run: npm run purge
            
        - name: deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./dist
          env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'